### ISSUE TITLE
Please add "how to run" to the readme

### ISSUE THREAD

**Issue by VeloSteve** [abdelkader/vCardEditor#10]
I have programmed in half a dozen languages and used Windows for decades, but I don't see a runnable program here.  A little hint in README.md about how to launch this would really help.  Thanks.

**Comment by blackhorus** [comment]
If you want a runnable version, check the relase section on github
https://github.com/abdelkader/vCardEditor/releases

Else, with download the code and compile it.. to get a runnable version

**Comment by abdelkader** [comment]
If you want a runnable version, check the relase section on github
https://github.com/abdelkader/vCardEditor/releases

Else, with download the code and compile it.. to get a runnable version

**Comment by VeloSteve** [comment]
Thanks for answering my issue.  I'm officially embarrassed that I didn't see the "releases" button.
