### ISSUE TITLE
Can I add an image in the Vcard Editor app

### ISSUE THREAD

**Issue by HESHAMAREBI** [abdelkader/vCardEditor#15]
السلام عليكم ورحمة الله وبركاته

Can I add an image in the Vcard Editor app

Best Regards,

**Comment by blackhorus** [comment]
السلام عليكم ورحمة الله وبركاته

Je vais voir si je peux rajouter cette fonctionnalité

**Comment by abdelkader** [comment]
و عليكم السلام
I managed to add the feature you requested.
