### ISSUE TITLE
Address Field not blank after selecting a contact without data entry in this particular Field

### ISSUE THREAD

**Issue by amaralmj** [abdelkader/vCardEditor#30]
After opening a vCard file that has multiple contact entries, and subsequently selecting various contacts, the following occurs:

When a different contact is selected, the GUI shows the address info last displayed for previous contact which had data in this field.

For example for a contact, say Contact #1,  with "1234 Main Street" correctly shown in the address field, when a different contact, say Contact #2,  is selected that is without entry for the address field will also contain "1234 Main Street" which almost certainly be incorrect for Contact #2.

Selecting what apparently is a random multiple selections of other contacts will eventually lead to clearing of this field for a contact without an address entry seems to be a way of getting the field cleared, until selecting another contract with valid address field data such as Contact #1, above.

I think fixing this issue would not required much of coding change.

**Comment by abdelkader** [comment]
I tried on my side with two contacts, one that is missing an address, but I didn't get what you described.  

Could you please paste an example for a vcf?

**Comment by amaralmj** [comment]
No because, when I tried that the following showed up:
We don't support that file type.  Try again with a GIF, JPEG, and several more .....................but not .vcf 
so I copied and renamed the file to have a .txt extension and attempted to paste it into this message.
The file name I think I have sent is Test - Copy.txt
It isn't clear to me if you'll be able to get it.   Please let me know if you don't.

The parent file of this one started by using the Export function within the Synology Contacts application. Synology Contacts runs under Synology DSM 7.1.1-42962 (latest) version running on my Synology Disk Station model DS918+.

If you rename "Test - Copy.txt" to "Test - Copy.vcf" you should be able to open it with your vCardeditor.  The problem can be observed if select Contact #1, then Contact #2, then Contact #1 (repeat).     By "selecting" , I mean placing the cursor over the contact field and then clicking.   NOT cycling the adjacent text box.   You should see an address (the same one associated with "Contact #2" appear in the address file for Contact #1, even though Contact #1 has no associated address.

Please let me know if what I've sent you helps, or if you need something else"

**Comment by abdelkader** [comment]
I don't seem to find any file attacheed to this discussion. Perhaps you could
- paste content directely (it'a a text file, so open it with notepad, and paste content here).
- Or put on some uploading hoting website (file.io  or  filebin.net..)

**Comment by amaralmj** [comment]
Let's try this....
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 16.5//EN
UID:b8879e63-b1ff-4284-a052-7ca589754081
FN:Contact #1
N: ; ;;;
REV:2023-06-17T17:08:34Z
TEL;TYPE=CELL,VOICE,pref:(800) 555-5555
END:VCARD
BEGIN:VCARD
VERSION:3.0
X-GROUP:
FN:Contact #2
UID:e5bba018-e4a6-4919-ab4d-7b0e4d315426
N:; ;;;
TEL;TYPE=CELL:(800) 777-7777
ADR;TYPE=HOME:;;Main Street\, Springfield;;;;
END:VCARD

**Comment by abdelkader** [comment]
a new version is published.  My mistake, I didn't perform a new release on my last commit. Could you please try and let me know

**Comment by amaralmj** [comment]
Downloaded 0.5.1 and received the following warning:

vCardEditor.exe is not commonly downloaded
and may be dangerous.

I ignored the warning and kept the file, and went ahead to test it.

The problem is fixed, but I think you should investigate why I received the above warning.

Regards,
Mike

**Comment by abdelkader** [comment]
It's a commun warning when a software don't have enough reputation with Microsoft SmartScreen.  This stackoverflow discussion summarize it : https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

I'll close the issue as fixed, and will see in the future if I can submit a final release.
