### ISSUE TITLE
the programme opens but...

### ISSUE THREAD

**Issue by DrVektor** [abdelkader/vCardEditor#37]
I haven't managed to run it yet. The programme opens, but I haven't managed to create any files, no matter where I pressed.

**Comment by abdelkader** [comment]
vCardEditor is used to open existing vcf file, not create them!

**Comment by DrVektor** [comment]
I created a text file and saved it as vcf, but when I tried to open it, it didn't react at all. Is this the wrong way to create a vcf file?

**Comment by abdelkader** [comment]
please read about here
https://en.wikipedia.org/wiki/VCard
