### ISSUE TITLE
Unhandled Exception: Value cannot be null. Parameter name: name

### ISSUE THREAD

**Issue by scootercommuter** [abdelkader/vCardEditor#9]
vcard export from Contacts app, Pixel 4.   VCF file could not be loaded.  I opened the VCF file with Notepad++, saw that the name was not null in the first few contacts.
BEGIN:VCARD
VERSION:2.1
N:theLastName;theFirstName;;;
FN:theFirstName theLastName
(etc)

**Comment by blackhorus** [comment]
Could you please join an example file, of course.. you can remove personal info, and just one or two entries..

**Comment by abdelkader** [comment]
Could you please join an example file, of course.. you can remove personal info, and just one or two entries..

**Comment by scootercommuter** [comment]
I did give you the first entry in the original submittal.  Here's the first few records, with the names changed.

BEGIN:VCARD
VERSION:2.1
N:Lastname1;Firstname1;;;
FN:Firstname1 Lastname1
TEL;CELL;PREF:888-555-1212
END:VCARD
BEGIN:VCARD
VERSION:2.1
N:Lastname2;Firstname2;;;
FN:Firstname2 Lastname2
TEL;X-iPhone;PREF:976-555-1313
EMAIL;PREF;HOME:nobody@nowhere.com
END:VCARD
BEGIN:VCARD
VERSION:2.1
N:;Firstname3;;;
FN:Firstname3
TEL;WORK;PREF:800-555-1314
ORG:TheOrg
END:VCARD
BEGIN:VCARD
VERSION:2.1
N:Lastname4;Firstname4;Middle4;;
FN:Wells Firstname4 Lastname4
TEL;WORK;PREF:800-555-1515
TEL;X-Fax:800-555-6565
ORG:Orgname
NOTE;ENCODING=QUOTED-PRINTABLE:=30=33=38=32=30=35=39=37=32=33=0A=4D=79=63=6F=76=65=72=61=67=65=69=6E=
=66=6F=2E=63=6F=6D=20=50=69=6E=20=57=46=39=33=36
END:VCARD

**Comment by scootercommuter** [comment]
Here is the above, as a file. Well, not possible to include the file, got an error message from GitHub that says "Something went really wrong, and we can't process that file.  Try again."  Tried again, repeats.  So you'll have to make do with the message above.

**Comment by abdelkader** [comment]
![image](https://user-images.githubusercontent.com/169070/151237283-30336ec0-2571-4768-a75b-56e7c5d34f3f.png)

It worked here.  You can try to upload your file elsewhere, and paste the link here..

**Comment by scootercommuter** [comment]
Closing the issue.  Didn't work for me with the full file.  I used an on-line conversion instead.  Sorry I can't help troubleshoot this.

**Comment by scootercommuter** [comment]
I think it might be one of the entries in the VCF file where the Name is null but the Organization is filled in.  See the title of the Issue, that was my error message.
